### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shu26docutar** [shu26docutar/furima-33478#15]
### URL
https://furima-33478.herokuapp.com

### Basic認証
ID     shuhei
pass 0926

### 出品者用のメールアドレスとパスワード
mail:  test3@test
pass: test33

### 購入者用のメールアドレスとパスワード
mail:  test4@test
pass: test44

### 購入用カードの番号・期限・セキュリティコード
4242424242424242
12/22
123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

- [ ] **商品の購入ができるようにしましょう**
現状、記載いただいたクレジットカード情報と配送先を入力しても購入ができません。
↓入力した配送先
<img width="443" alt="スクリーンショット 2021-01-23 15 37 13" src="https://user-images.githubusercontent.com/62644781/105571298-52299f80-5d92-11eb-993e-e780f88396e7.png">


上記に関連している項目の挙動確認は、修正後に行わせていただきます。

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shu26docutar** [comment]
herokuに環境変数を設定していましたが、正常にpushできていなかったことが原因でクレジット処理ができていなかったみたいです。

再度ご確認お願いします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、問題なく商品が購入できるようになっていました！

今回新たに修正をお願いしたい箇所がありましたので、ご確認をお願いします。
[修正箇所]

- [ ] **売却済みの商品は、画像上に「sould out」の文字が表示されるようにしましょう**
　-一覧ページ、商品詳細ページ共に表示されておりません

- [ ] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**
　-出品者が、自身の出品した売却済みの商品の商品情報編集ページにURLを直接入力して遷移しようとすると、編集ページに遷移、編集できてしまいます 

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shu26docutar** [comment]
修正いたしました！ご確認宜しくお願い致します！！

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、修正箇所全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/62644781/105624103-7b196580-5e62-11eb-8bf1-598552e188e5.png)
